name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: "0"
      - name: Install system deps
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential \
            dh-autoreconf \
            libjansson-dev \
            libmagic-dev \
            pkg-config \
            libpcap-dev \
            libcap-dev \
            curl \
            bison
      - name: Install yara
        run: |
          cd /tmp
          wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.3.2.tar.gz
          tar -zxf v4.3.2.tar.gz
          cd yara-4.3.2
          ./bootstrap.sh
          ./configure --prefix=$HOME/.local/yara --disable-dotnet --enable-magic --enable-cuckoo --disable-shared --enable-static
          make -j$(nproc)
          make install
          cd $HOME/.local
          tar -czf yara.tar.gz yara
          export PKG_CONFIG_PATH="$HOME/.local/yara/lib/pkgconfig"

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          only-new-issues: true
